package_name: regression_model

data_file: titanic.csv
pipeline_save_file: Jany_titanicModel_v


numerical_variables: 
    - age 
    - fare
    
categorical_variables:
    - sex 
    - cabin
    - embarked
    - title

cabin:
    - cabin


#Variables:
target: survived 
features:
   	- pclass
   	- sex
   	- age
   	- sibsp
   	- parch
   	- fare
   	- cabin
   	- embarked
   	- title
    

# Model params
test_size: 0.2
random_state: 777

    